theme = "PaperMod"
baseURL = "https://Eliorion/"
title = 'Eliorion blog'

[params]
  showReadingTime = true
  showBreadCrumbs = true
  showPostNavLinks = true
  ShowLanguageSelector = true

defaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "English"
    weight = 1

  [languages.fr]
    languageName = "FranÃ§ais"
    weight = 2

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 19

[[menu.main]]
  identifier = "topics"
  name = "Topics"
  url = "/topics/"
  weight = 16

[[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 15

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 17

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 18

[permalinks]
posts = "/posts/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"
  topic = "topics"   # â† on peut ajouter "topics" si on veut un regroupement spÃ©cifique
  project = "projects"

[languages.en.params.homeInfoParams]
  Title = "ğŸ‘‹ Welcome the Eliorion Blog"
  Content = "Here I share my journey in homelab, Kubernetes, and engineering management. ğŸš€"

[languages.fr.params.homeInfoParams]
  Title = "ğŸ‘‹ Bienvenue sur le blog d'Eliorion"
  Content = "Je partage ici mon parcours dans le domaine des Homelab (laboratoires domestiques), de Kubernetes et du managelent de projet. ğŸš€"
